Add support for external tickets company details
WISVCH/symposium pull request #116
Opened 2017-04-22 18:21 UTC by TimvdLippe

Since this is extra necessary information and there is 1 external ticket sold. We still need to contact this person with the details, since this PR was not open before :sob:

2017-04-24 16:22 UTC, martijnjanssen requested changes
Looks like we can improve here :)

2017-04-24 16:22 UTC, martijnjanssen commented on src/symposium-tickets/symposium-tickets-button.html
> +          }
The else block should hide this portion of the page again.

2017-04-24 16:22 UTC, martijnjanssen commented on src/symposium-tickets/symposium-tickets-button.html
> +        var companyName = this.parentNode.querySelector('input[name="name"]').value;
I believe this should be name=companyname

2017-04-29 13:52 UTC, TimvdLippe commented
I would vouch for closing this one, as it is too risky and too late now. We can improve for next year nonetheless.

2017-05-01 19:08 UTC, closed without merging