Board of Recommendation
WISVCH/symposium pull request #40
Opened 2016-11-01 21:03 UTC by royklip

Add the Board of Recommendation between the information page card and the location page card.

2016-11-01 21:04 UTC, TimvdLippe commented
You need to rebase this PR, because some commits should not be in this diff.

2016-11-02 19:15 UTC, mgajanssen commented
I think this is because the old one was merged into the new one that contained my commit.

2016-11-04 16:22 UTC, mgajanssen commented
It might be nice to add a minimum width to the company logos, currently, the distribution of the logos is not very even. Other than that, looks good!

2016-11-07 10:17 UTC, martijnjanssen requested changes
Changes all look very good, just two really small remarks and we are good to go!

2016-11-07 10:17 UTC, mgajanssen commented on src/symposium-app/symposium-recommendations.html
> +                margin: 0 5px 0 5px;
You can remove the padding and add those `10px` to the margin: `margin: 10px 15px;`

2016-11-07 10:17 UTC, mgajanssen commented on src/symposium-app/symposium-recommendations.html
> +                flex-basis: 150px;
I would suggest increasing the flex basis to `175px`, this improves the formatting of the text underneath the images.

2016-11-07 16:45 UTC, martijnjanssen approved these changes

2016-11-07 16:45 UTC, martijnjanssen commented
All looks good to me!

2016-11-07 16:46 UTC, merged