Scaffold indexes
WISVCH/symposium pull request #52
Opened 2017-02-09 15:33 UTC by TimvdLippe

Warning: this is a big PR. Please review one commit at a time.

Most notably:
* A new version of `polymer-build` to fix some minification and issues
* Rename files (large amount of diff, but should be few changes)
* Introduce a new script `scaffold-indexes.js`. This file takes each top custom element per path and generates a special index.html. This makes sure that loading is blazingly fast.
* Removed a lot of unnecessary usages of `paper-`elements by normal HTML elements.
* Rewrote program to use a table instead. This is semantically correct and fixes styling
* Remove `app-header` and friends and replace with a simply styled `<header>`
* Remove bindings in pages and replace with actual content. This is because we can not use the binding system when scaffolding. It is also faster :tada: 
* Add a yarn file as we/I use Yarn

2017-02-13 13:10 UTC, martijnjanssen requested changes
Can't we use lambdas in the js? I would assume we can since we are now using the babel compiler. Should we also have a [.babelrc](http://babeljs.io/docs/usage/babelrc/) in the project now?

Are we actually using the slider that is listed in the imports?

As for visually testing, it all looks pretty good, still some things bother me:
- ~The min-width of the content is too wide for all mobile devices~
- ~The program-table seems to be missing~

Other than that, it looks solid!

2017-02-13 13:10 UTC, martijnjanssen commented on README.md
> +This will create a `build/` folder containing an unbundled builds,
Does it create one or two builds here? Isn't it supposed to be a singular?

2017-02-13 13:22 UTC, martijnjanssen commented on src/symposium-homepage.html
> +<link rel="import" async href="../bower_components/iron-icons/iron-icons.html">
Nice, I just noticed this one.

2017-02-13 13:58 UTC, TimvdLippe commented
@martijnjanssen We are using babeli as minifier, we do not transpile. Therefore we can sadly not use ES6 features yet.

Could you clarify the min-width comment?

Yes the program table isn't working due to an error with resolution. Trying to look for a solution atm

2017-02-14 11:05 UTC, martijnjanssen commented
The min width is now fixed, including some layout improvements for small devices. 

The program page is now fixed in #53. Still have to add the shadow to the program section though. Are we merging this PR first or are we merging that one into this one? I would prefer merging #53 in this one and then fixing the shadow on the timetable.

2017-02-14 11:05 UTC, martijnjanssen commented
@TimvdLippe The min width is now fixed, including some layout improvements for small devices. 

The program page is now fixed in #53. Still have to add the shadow to the program section though. Are we merging this PR first or are we merging that one into this one? I would prefer merging #53 in this one and then fixing the shadow on the timetable.

2017-02-14 12:24 UTC, martijnjanssen approved these changes

2017-02-14 14:47 UTC, merged